### ISSUE TITLE
文字多了无法一体化导出，PDF会分割，图像只能导出一部分

### ISSUE THREAD

**Issue by web1230** [MichaelLaw2003/amber-vertical-typora-theme#5]
1. 文字多了无法一体化导出，PDF会分割，能不分页导出吗？
2. 图像只能导出一部分，无法全部导出
3. 数字1.2.3.4.5.6.7.8.9不能竖向显示
4. 导出网页 也没法左右拉动进度条 看全部内容

**Comment by MichaelLaw2003** [comment]
`1.` and `2.` are problems caused by pandoc.
You have already reported `3.` in a seperate issue. Please check my reply out there.
`4.` is a problem caused by the editor. Please turn to Typora and ask for an official support of vertical typography.
